### PR TITLE
Fix installation under pip 10

### LINKED ISSUE #20: setup.py incompatible with pip 10
Pip 10 was recently released.

The line `from pip.req import parse_requirements` in setup.py no longer works.

```
Collecting somecomfort==0.5.0 (from -r /home/ubuntu/home-assistant/requirements_test_all.txt (line 183))
  Downloading somecomfort-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6749n3pf/somecomfort/setup.py", line 1, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
```

### PR DESCRIPTION
**Pull request by balloob**
Fixes #20

### CODE REVIEW

**Comment by balloob** [comment]
So fast ⚡️ Thanks

**Comment by kk7ds** [comment]
Pushed to pypi as 0.5.1. Thanks for making it easy :)

**Comment by MartinHjelmare** [comment]
Something seems to have gone wrong with the pypi release, cause the 0.5.1 tar.gz still contains the old setup.py.

**Comment by kk7ds** [comment]
Sorry, I'm an idiot. Better with 0.5.2?

**Comment by MartinHjelmare** [comment]
Great! That works, thanks!

**Comment by balloob** [comment]
Updated my pr https://github.com/home-assistant/home-assistant/pull/13940

**Pull request merged**
